name: Origami
version: 1.0.0
main: com.origamimc.main.PaperOrigamiMain
description: Run other jar files inside of Paper, Velocity or Waterfall servers
api-version: '1.20'
author: cometcake575

permissions:
  origami.command:
    description: Run the /origami command
    default: op

commands:
  origami:
    aliases: origami-paper
    description: Give an input to a running program
    usage: /<command> <instance> <input>
    permission: origami.command
